-- A-17 phase 1 (flag OFF): schema + enum-aware code only, per a17-design.md
-- rev 5 §2/§9. Purely additive — no existing data changes, no backfill. The
-- `SubmissionStatus.Verified` enum value is a SEPARATE migration
-- (20260926120000): it can't be added and used in the same transaction (✎D2).
--
-- Every statement is guarded, so re-running this file by hand is a no-op
-- (prisma migrate deploy already skips it once recorded in _prisma_migrations).

-- CreateEnum
DO $$ BEGIN
  CREATE TYPE "SubmissionFlow" AS ENUM ('Legacy', 'ClosedDeal');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateEnum
DO $$ BEGIN
  CREATE TYPE "QuotationStatus" AS ENUM ('Issued', 'Converted', 'Void');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- AlterTable: sales_submissions — flow defaults every existing row to Legacy in
-- one statement (✎D3: this default stays permanently; new code sets
-- ClosedDeal explicitly on create, never relies on the column default).
ALTER TABLE "sales_submissions"
  ADD COLUMN IF NOT EXISTS "flow" "SubmissionFlow" NOT NULL DEFAULT 'Legacy',
  ADD COLUMN IF NOT EXISTS "rejected_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "content_version" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "transaction_code" TEXT,
  ADD COLUMN IF NOT EXISTS "verified_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "verified_by" UUID,
  ADD COLUMN IF NOT EXISTS "quotation_id" UUID;

-- transaction_code is nullable + unique: Postgres treats every NULL as
-- distinct, so existing (and future Legacy) rows with no code coexist fine.
CREATE UNIQUE INDEX IF NOT EXISTS "sales_submissions_transaction_code_key" ON "sales_submissions"("transaction_code");

-- CreateSequence: quotation codes (QUO-nnnn), same pattern as transaction_code_seq.
CREATE SEQUENCE IF NOT EXISTS quotation_code_seq START 1;

-- CreateTable: quotations (new, no money — never referenced by the engine).
CREATE TABLE IF NOT EXISTS "quotations" (
    "id" UUID NOT NULL,
    "quotation_code" TEXT NOT NULL,
    "associate_id" UUID NOT NULL,
    "client_name" TEXT NOT NULL,
    "client_contact" TEXT,
    "quote_date" DATE NOT NULL,
    "valid_until" DATE,
    "lines" JSONB NOT NULL,
    "total" DECIMAL(14,2) NOT NULL,
    "status" "QuotationStatus" NOT NULL DEFAULT 'Issued',
    "created_by" UUID,
    "voided_at" TIMESTAMP(3),
    "voided_by" UUID,
    "void_reason" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "quotations_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "quotations_quotation_code_key" ON "quotations"("quotation_code");
CREATE INDEX IF NOT EXISTS "quotations_associate_id_idx" ON "quotations"("associate_id");

DO $$ BEGIN
  ALTER TABLE "quotations" ADD CONSTRAINT "quotations_associate_id_fkey"
    FOREIGN KEY ("associate_id") REFERENCES "associates"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- sales_submissions.quotation_id -> quotations.id, added after the table
-- exists. SET NULL: an informational link only (the submission's own lines
-- are authoritative, §2), so deleting a quotation must not block or cascade.
CREATE INDEX IF NOT EXISTS "sales_submissions_quotation_id_idx" ON "sales_submissions"("quotation_id");

DO $$ BEGIN
  ALTER TABLE "sales_submissions" ADD CONSTRAINT "sales_submissions_quotation_id_fkey"
    FOREIGN KEY ("quotation_id") REFERENCES "quotations"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- AlterTable: products — per-product required-document checklist (ⓢ Q6) and
-- the Pet Ash auto-generation flag (Q4). Empty list / false for every
-- existing product: nothing becomes required or auto-generated by default.
ALTER TABLE "products"
  ADD COLUMN IF NOT EXISTS "required_documents" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "requires_ashes_agreement" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable: submission_documents — tags an uploaded file with the
-- required-document key it satisfies (G3). NULL for every existing document.
ALTER TABLE "submission_documents"
  ADD COLUMN IF NOT EXISTS "requirement_key" TEXT;

-- AlterTable: sales_transactions — the frozen commission-parties snapshot
-- (ⓢ Q33c). NEW SALES ONLY: NULL for every existing (legacy) transaction, no
-- backfill — legacy transactions keep the live upline/split resolution.
ALTER TABLE "sales_transactions"
  ADD COLUMN IF NOT EXISTS "commission_parties" JSONB;

-- AlterTable: pets_ashes_agreements — the signed-terms snapshot + PDF hash
-- (C2), so an edit after signing can be detected and the signature voided.
-- signature_version starts at 0 for every existing row (none has been
-- re-signed); it's bumped only when a signature is voided and re-taken.
ALTER TABLE "pets_ashes_agreements"
  ADD COLUMN IF NOT EXISTS "signed_terms" JSONB,
  ADD COLUMN IF NOT EXISTS "signed_pdf_sha256" CHAR(64),
  ADD COLUMN IF NOT EXISTS "signature_version" INTEGER NOT NULL DEFAULT 0;

-- Note: split_exception_* (including split_exception_snapshot, C4) already
-- exist on sales_submissions (B-S6, 20260926100000_bs6_split_exception).
-- A-17 only CONSUMES them as gate G2 — nothing to add here.
