/**
 * Export-stamp backfill for payouts Approved before bank-file batches existed.
 * See server/payouts/export-stamp-plan.ts for the rule. Run AFTER the M5 migration and
 * BEFORE the first bank file is generated (payout screens frozen; see the runbook).
 *
 * DRY RUN (default) — needs a read-only DB session, writes nothing:
 *   DATABASE_URL="<url>&options=-c%20default_transaction_read_only%3Don" \
 *     pnpm tsx scripts/backfill-export-stamp.ts           # summary + one line per payout
 *   (…same…) pnpm tsx scripts/backfill-export-stamp.ts --json
 *
 * APPLY — only on the owner's go, with the stamp count the reviewed dry run printed:
 *   DATABASE_URL="<url>" pnpm tsx scripts/backfill-export-stamp.ts --apply --confirm=<N>
 * One transaction; refuses if the plan no longer stamps exactly N payouts, or if a
 * bank file was already generated by the new code. A re-run stamps nothing.
 *
 * Output contains ids, months and amounts only — no names or other personal data.
 */
import { PrismaClient } from "@prisma/client";
import { applyExportStamp, planExportStamp } from "@/server/payouts/export-stamp-plan";

async function sessionReadOnly(db: PrismaClient): Promise<boolean> {
  const [row] = await db.$queryRaw<{ transaction_read_only: string }[]>`SHOW transaction_read_only`;
  return row?.transaction_read_only === "on";
}

async function main() {
  const apply = process.argv.includes("--apply");
  const confirmArg = process.argv.find((a) => a.startsWith("--confirm="));
  const db = new PrismaClient();
  try {
    const ro = await sessionReadOnly(db);
    if (!apply && !ro) {
      throw new Error("Dry run needs a read-only session: append options=-c%20default_transaction_read_only%3Don to DATABASE_URL.");
    }
    const plan = await planExportStamp(db);
    const stamp = plan.rows.filter((r) => r.action === "stamp");

    if (!apply) {
      if (process.argv.includes("--json")) {
        console.log(JSON.stringify(plan, null, 2));
        return;
      }
      const byReason = new Map<string, number>();
      for (const r of plan.rows) byReason.set(`${r.action} ${r.reason}`, (byReason.get(`${r.action} ${r.reason}`) ?? 0) + 1);
      console.log(`unstamped Approved payouts: ${plan.rows.length}; would stamp: ${stamp.length}; needs review: ${stamp.filter((r) => r.review).length}`);
      console.log(`existing bank-file batches: ${plan.existingBatches}${plan.existingBatches > 0 ? "  <-- a new export already ran: apply will refuse" : ""}`);
      for (const [k, n] of byReason) console.log(`  ${k}: ${n}`);
      for (const r of plan.rows) {
        console.log([r.action, r.reason, r.review ? "REVIEW" : "", r.payoutMonth, `seq${r.seq}`, r.payoutId, r.total, r.lastFileAt ?? "-"].join("\t"));
      }
      console.log(`\nTo apply (owner's go only): --apply --confirm=${stamp.length}`);
      return;
    }

    if (ro) throw new Error("--apply needs a writable session (drop default_transaction_read_only from DATABASE_URL).");
    const raw = confirmArg?.slice("--confirm=".length) ?? "";
    const expected = /^\d+$/.test(raw) ? Number(raw) : NaN;
    if (!Number.isInteger(expected)) throw new Error("--apply needs --confirm=<N>, the stamp count from the reviewed dry run.");
    if (expected !== stamp.length) throw new Error(`refused: the plan now stamps ${stamp.length}, not ${expected}. Re-run the dry run and review it.`);
    const result = await applyExportStamp(db, null, expected);
    console.log(`stamped ${result.stamped} payout(s) into ${result.batches} legacy batch(es).`);
  } finally {
    await db.$disconnect();
  }
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
